spring.application.name=bookLibrary
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

app.cors.allowed-origin=http://localhost:5173

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=10m

spring.config.import=vault://

spring.cloud.vault.host=localhost
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.token=root

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=application

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always